### ISSUE TITLE
可以处理网络加载图片吗？

### ISSUE THREAD

**Issue by feisher** [yingLanNull/ShadowImageView#1]
比方说列表加载网络图片，如何使用呢？

**Comment by yingLanNull** [comment]
本组件不是很完善，暂未考虑对列表批量图片的处理，也没提供相关方法，后期会优化该库。

**Comment by SheepYang1993** [comment]
目前不支持加载网络图片？

**Comment by yingLanNull** [comment]
是的，由于实现方式的原因暂不支持，目前可以通过三方工具(如:Android-Universal-Image-Loader)加网络图片完成之后转为drawable类型的进行设置。
