### ISSUE TITLE
能否支持彩色阴影的拓展，根据图片颜色产生阴影

### ISSUE THREAD

**Issue by hzq19920817** [yingLanNull/ShadowImageView#17]
![default](https://user-images.githubusercontent.com/14231403/32158926-102a2230-bd86-11e7-9e58-42328c0e7fcf.png)

**Comment by yingLanNull** [comment]
因为实现方式的问题，不是将图片放大加模糊效果，而是取了图片的主色调绘在了下面。

**Comment by lozn00** [comment]
希望对外提供image,不然imageloader等 都需要用另外一种方法改变图片。
