### ISSUE TITLE
demo 安装后一打开就闪退

### ISSUE THREAD

**Issue by AndroidDevo** [yingLanNull/ShadowImageView#2]
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.yinglan.shadowdemo/com.yinglan.shadowdemo.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.yinglan.shadowdemo.MainActivity" on path: DexPathList[[zip file "/data/app/com.yinglan.shadowdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yinglan.shadowdemo-1/lib/arm64, /system/lib64, /vendor/lib64]]

**Comment by yingLanNull** [comment]
编译的apk有问题，已重新编译上传，请再次下载体验，感谢支持。
