### ISSUE TITLE
测试Android4.3不能显示图片，6.0可以。且与原生ImageView设置一样大小，此ShadowImageView显示大小比较小。

### ISSUE THREAD

**Issue by RealMoMo** [yingLanNull/ShadowImageView#20]
测试Android4.3不能显示图片，6.0可以。且与原生ImageView设置一样大小，此ShadowImageView显示大小比较小。

**Comment by yingLanNull** [comment]
因为实现方式的问题实际显示大小会比预设小一些，目前还没有找到更好的方式让图片大小变一致
