### ISSUE TITLE
StateListDrawable 会报类型转换错误

### ISSUE THREAD

**Issue by wonxll** [yingLanNull/ShadowImageView#4]
修改的

if (((ImageView) view).getDrawable() instanceof ClipDrawable) {
      rgb = Color.parseColor("#8D8D8D");
      shadowPaint.setShadowLayer(radius, 0, shadowColor, getDarkerColor(rgb));
      } else if (((ImageView) view).getDrawable() instanceof ColorDrawable) {
               rgb = ((ColorDrawable) ((ImageView) view).getDrawable()).getColor();
               shadowPaint.setShadowLayer(40, 0, 28, getDarkerColor(rgb));
      } else {
             **if (((ImageView) view).getDrawable() instanceof StateListDrawable) {
                          StateListDrawable drawable = (StateListDrawable) ((ImageView) view).getDrawable();
                          bitmap = ((BitmapDrawable) drawable.getCurrent()).getBitmap();
                } else {
                           bitmap = ((BitmapDrawable) ((ImageView) view).getDrawable()).getBitmap();
                          }**
.............
}

**Comment by yingLanNull** [comment]
@wonxll 感谢支持，没有添加一些特殊的类型，已经修改支持，对一些非图片资源不能很好的支持可能与实现方式有关，后续有时间会考虑更改成其它实现形式。
