### ISSUE TITLE
内存抖动

### ISSUE THREAD

**Issue by wonxll** [yingLanNull/ShadowImageView#8]
内存抖动，不知道你发现没有...ShadowImageView dispatchDraw()死循环

**Comment by yydcdut** [comment]
`setLayerType(LAYER_TYPE_SOFTWARE, null);`
关闭硬件加速是一个配置功能，应该放在构造函数中
`((RoundImageView) view).setRound(shadowRound)`
在 dispatchDraw 的最后调用了 RoundImageView#setRound() 的方法，该方法调用了 `invalidate()` 方法，导致重新绘制，又会进入到 ShadowImageView 的 dispatchDraw 中

**Comment by wonxll** [comment]
是这样的...

**Comment by yingLanNull** [comment]
@wonxll @yydcdut 首先感谢两位支持，我也发现了这个问题，本来想换其他的实现方式，但由于这段时间一直在忙即没有解决这个问题也没有尝试其他方式，今天有时间我会根据你们提供的信息先解决这个。

**Comment by yingLanNull** [comment]
@yydcdut  抽时间使用了取巧的办法解决了重绘

**Comment by yydcdut** [comment]
还有其他的问题额，我也在这跟你说一下吧
`setImageResource()` 和 `setImageDrawable()` 方法不需要再调用 `invalidate()` 方法，`RoundImageView#setImageResource()` 里面就进行了刷新操作

```
int N = getChildCount();

                for (int i = 0; i < N; i++) {
                    View view = getChildAt(i);
                    if (i != 0) {
                        removeView(view);
                        continue;
                    }
                }
```
这段代码潜在 IndexOutOfBoundsException 的情况
比如 N 为 3 ，当 i 为 1 的时候，remove 掉了，那么此时 `getChildCount()` 为 2，此时 i++，为 2，小于 N，此时 `getChildAt(2)` 会数组越界，恩，应该是这样的（认真脸）

**Comment by wonxll** [comment]
我一直不知道这段代码的目的是什么。。。initView（）只执行一次，那么addView（）也就只执行了一次，getChildCount（）也只有一个啊...你试试不要这段代码，会是什么样

**Comment by yingLanNull** [comment]
@yydcdut 学习了，多谢。这里不会发生越界，之所以这样是因为getChildAt(index)可以容index越界的错，removeView(view)接受null也不会有问题，不过还是修改了一下代码。 @wonxll 因为这个自定义的组件继承的是RelativeLayout，不排除会在布局或者代码往里添加View的可能性，所以就来了这么一下。

**Comment by wonxll** [comment]
你怎么确认你的RoundImageView 是第一个加进去的呢？所以你这段代码....

**Comment by wonxll** [comment]
if(getChildAt(i) instanceof RoundImageView)    如果非要弄，应该这样吧

**Comment by yingLanNull** [comment]
初始化的时候就添加进去的，正常情况下应该没有比它还早的了吧，不知道还有没有其他的特殊的情况。

**Comment by wonxll** [comment]
这倒是...哈哈（尴尬）
